---
on:
  workflow_dispatch:
  push:
    paths:
      - 'ide/docker/**'
      - 'ide/provisioning/**'
      - '.github/workflows/build-container.yml'
    paths-ignore:
      - 'cloud/**'
      - 'doc/**'
      - 'fuzzer/**'
      - 'kobo/**'
      - 'python/**'
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-unix.yml'
      - '.readthedocs.yaml'

jobs:
  xcsoar-docker-env:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGENAME: xcsoar-build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - id: lc_repository_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}
      - name: build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          context: ./ide
          file: ./ide/docker/Dockerfile
          tags: ghcr.io/${{ steps.lc_repository_name.outputs.lowercase }}/xcsoar-build:latest
          cache-from: type=registry,ref=ghcr.io/${{ steps.string.outputs.lowercase }}/xcsoar-build:latest
          cache-to: type=inline
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
